# Generated by Django 5.0.8 on 2026-05-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_customers_database'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
