# Generated by Django 5.0.8 on 2026-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_customer_user_order_customer_geocoded_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Casa de Kebab Turco', max_length=120)),
                ('phone', models.CharField(default='+34 613 473 564', max_length=30)),
                ('subtitle_es', models.CharField(default='Kebab fresco, pedidos rápidos, auténtico sabor turco', max_length=200)),
                ('subtitle_en', models.CharField(default='Fresh kebab, fast orders, authentic Turkish taste', max_length=200)),
                ('address', models.CharField(default='Calle García Lorca, 1, 37004 Salamanca, España', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
